### ISSUE TITLE
Confusion about data units

### ISSUE THREAD

**Issue by ghost** [diegommcc/digitalDLSorteRmodels#1]
Hi DigitalDLSorter team，
I am very interested in your DigitalDLSorter, this idea deeply attracted me. When I read your paper and github code, I have two confusion and need to consult you.
(1) Your article mentions converting TCGA data to tpm as the data unit, but in your code description it mentions cpm, whether you are using cpm or tpm.
(2) I think the dimensions of bulk data and single-cell data are different. How do you ensure that your integrated pseudo-bulk expression profile is in the same order of magnitude as the real bulk data expression profile?

Picture from **Digitaldlsorter: Deep-Learning on scRNA-Seq to Deconvolute Gene Expression Data**
![image](https://user-images.githubusercontent.com/75767091/139577794-457a90bc-1ac5-468d-8437-e3e8fec8d2e6.png)
Picture from https://github.com/cran/digitalDLSorteR
![image](https://user-images.githubusercontent.com/75767091/139577806-02e4a3cf-cfde-4f6e-ba09-927121f6ef5c.png)

**Comment by diegommcc** [comment]
This issue was solved in diegommcc/digitalDLSorteR#1.
